apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasource
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: {{ .Values.datasource.url }}
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dashboard-provider
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: default
        type: file
        options:
          path: /var/lib/grafana/dashboards
