apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
