apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name www.simplewebaccess.com;

        location /api/ {
            proxy_pass       http://{{ .Values.backend.host }}:{{ .Values.backend.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass       http://{{ .Values.frontend.host }}:{{ .Values.frontend.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Prometheus
    # resolver + set $upstream = lazy DNS resolution so nginx won't fail at startup if service isn't running yet
    server {
        listen 80;
        server_name prometheus.simplewebaccess.com;
        resolver {{ .Values.dnsResolver }} valid=5s;

        location / {
            set $upstream http://prometheus-svc.default.svc.cluster.local:9090;
            proxy_pass       $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Grafana
    server {
        listen 80;
        server_name grafana.simplewebaccess.com;
        resolver {{ .Values.dnsResolver }} valid=5s;

        location / {
            set $upstream http://grafana-svc.default.svc.cluster.local:3000;
            proxy_pass       $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # ArgoCD
    server {
        listen 80;
        server_name argocd.simplewebaccess.com;
        resolver {{ .Values.dnsResolver }} valid=5s;

        location / {
            set $upstream http://argocd-server.argocd.svc.cluster.local:80;
            proxy_pass       $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
